---
# tasks file for roles/prometheus

- name: Actualización dos repositorios e instalación de prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: reiniciar_prometheus

- name: Arquivo de configuración do prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: recargar_prometheus

- name: Iniciar prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- meta: flush_handlers

