- hosts: cliente_windows
  gather_facts: no

  tasks:
  - name: Instalación de Chocolatey
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - name: Instalación de VCL
    win_chocolatey:
      name:
      - vlc