- hosts: dns_principal
  become: yes
  tasks:
  - name: Actualizaci贸n dos repositorios e instalaci贸n do servizo DNS
    apt:
      name: bind9
      state: latest
      update_cache: true
  - name: Copia do ficheiro default do servizo
    copy:
      src: /proxecto/DNS/named
      dest: /etc/default/named
      mode: u=rw,g=r,o=r
  - name: Copia do ficheiro de configuraci贸n de zonas
    copy:
      src: /proxecto/DNS/named.conf.local
      dest: /etc/bind/named.conf.local
      mode: u=rw,g=r,o=r
  - name: Copia do ficheiro de opci贸ns do servizo
    copy:
      src: /proxecto/DNS/named.conf.options
      dest: /etc/bind/named.conf.options
      mode: u=rw,g=r,o=r
  - name: Copia do ficheiro de zona directa
    copy:
      src: /proxecto/DNS/db.proxecto.marta
      dest: /etc/bind/db.proxecto.marta
      mode: u=rw,g=r,o=r
  - name: Copia do ficheiro de zona inversa
    copy:
      src: /proxecto/DNS/db.10.0.2
      dest: /etc/bind/db.10.0.2
      mode: u=rw,g=r,o=r
  - name: Reinicio do servizo
    systemd:
      name: named
      state: restarted