---
# handlers file for roles/prometheus

- name: reiniciar_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: recargar_prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200

