- hosts: proxecto
  become: yes
  tasks:
  - name: Actualización dos repositorios e instalación do servizo DHCP
    apt:
      name: dhcpd
      state: latest
      update_cache: true
  - name: Copia do arquivo de configuración
    copy:
      src: /proxecto/DHCP/dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: u=rw,g=r,o=r
  - name: Reinicio do servizo
    systemd:
      name: dhcpd
      state: restarted