- hosts: dns_principal
  become: yes
  tasks:
  - name: Actualizaci贸n dos repositorios e instalaci贸n do servizo DHCP
    apt:
      name: isc-dhcp-server
      state: latest
      update_cache: true
  - name: Copia do ficheiro de configuraci贸n default
    copy:
      src: /proxecto/DHCP/isc-dhcp-server
      dest: /etc/default/isc-dhcp-server
      mode: u=rw,g=r,o=r
  - name: Copia do ficheiro de configuraci贸n principal
    copy:
      src: /proxecto/DHCP/dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: u=rw,g=r,o=r
  - name: Reinicio do servizo DHCP
    service:
      name: isc-dhcp-server
      state: restarted 